[workspace]
members = [
    ".",
    "crates/shared-types",
    "crates/dfir-evtx",
    "crates/recon-net",
    "crates/plugin-sdk",
    "plugins/sample-filter",
]
resolver = "2"

[package]
name = "larp"
version = "0.1.0"
edition = "2021"
authors = ["Ventie"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
clap_complete = "4.4"
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
config = "0.14"
directories = "5.0"
shared-types = { path = "crates/shared-types" }
dfir-evtx = { path = "crates/dfir-evtx" }
recon-net = { path = "crates/recon-net"}
ratatui = "0.26"
crossterm = "0.27"
wasmtime = "19.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "stream", "json"] }
futures-util = "0.3"
axum = "0.7"
tokio-stream = "0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true
panic = "abort"

[profile.release.package."*"]
opt-level = "z"
